### ISSUE TITLE
Health check conflicts for same path in Helm chart.

### ISSUE THREAD

**Issue by bohdantverdyi** [cryptlex/helm-charts#2]
**Issue:**
The current Helm chart configuration sets up a health check at /v3/status within the Ingress definition, without specifying a host. Consequently, any domain with this path will be routed to the Cryptlex service. However, this approach encounters issues when other domains also utilize the same path, leading to conflicts and ineffective traffic routing.

**Impact:**
Routing Reliability: Conflicting paths result in unpredictable routing behavior.
Service Availability: Inability to properly route traffic affects services using similar paths.
Operational Complexity: Troubleshooting becomes challenging due to inconsistent routing patterns.

**Proposed Solution:**
To resolve this issue, we should refactor the Ingress configuration to handle path conflicts gracefully. This may involve revising the path structure or implementing a more flexible routing mechanism to accommodate multiple domains with similar paths.

**Steps to Reproduce:**
Deploy the Helm chart with the current Ingress configuration.
Configure multiple domains with overlapping paths (/v3/status).
Observe the impact of conflicting paths on routing behavior and service availability.

**Comment by adnan-kamili** [comment]
@bohdantverdyi we have added `enableStatusPath` in values.yml to the ingress. You can set it to false to disable this catch all status endpoint. Hope this helps.

Please close the issue if it solves your problem.

**Comment by bohdanbinahai** [comment]
Thank you

**Comment by bohdantverdyi** [comment]
> @bohdantverdyi we have added `enableStatusPath` in values.yml to the ingress. You can set it to false to disable this catch all status endpoint. Hope this helps.
> 
> Please close the issue if it solves your problem.

Thank you
